In [69]:
import sklearn.metrics
import tensorflow as tf
import tensorflow.keras.activations as activations
import tensorflow.keras.layers as layers
import tensorflow.keras.losses as losses
import tensorflow.keras.metrics as metrics
import tensorflow.keras.optimizers as optimizers

In [4]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
y_test.shape

(10000,)

In [37]:
X_train_scaled = X_train / 255.0
X_test_scaled = X_test / 255.0

In [57]:
model = tf.keras.models.Sequential()

In [58]:
model.add(layers.Flatten())
model.add(layers.Dense(512))
model.add(layers.Activation(activations.relu))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(10))
model.add(layers.Activation(activations.softmax))

In [59]:
model.compile(loss=losses.SparseCategoricalCrossentropy, optimizer=optimizers.Adam(), metrics=[metrics.SparseCategoricalAccuracy()])

In [60]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 0.3663 - sparse_categorical_accuracy: 0.8923
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0986 - sparse_categorical_accuracy: 0.9698
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0668 - sparse_categorical_accuracy: 0.9795
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0488 - sparse_categorical_accuracy: 0.9847
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0386 - sparse_categorical_accuracy: 0.9876
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0315 - sparse_categorical_accuracy: 0.9899
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0298 - sparse_categorical_accuracy: 0.9897
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0238 - sparse_categorical_accuracy: 0.9918
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 0.0226 - sparse_categorical_accuracy: 0.9928
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━

In [62]:
model.evaluate(X_train_scaled, y_train)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 0.0106 - sparse_categorical_accuracy: 0.9964


[0.010138855315744877, 0.9965333342552185]

In [63]:
model.evaluate(X_test_scaled, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0885 - sparse_categorical_accuracy: 0.9777


[0.07718248665332794, 0.9810000061988831]

In [67]:
y_pred = model.predict(X_test_scaled).argmax(axis=1)
y_pred

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([7, 2, 1, ..., 4, 5, 6])

In [68]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [70]:
sklearn.metrics.multilabel_confusion_matrix(y_test, y_pred)

array([[[9006,   14],
        [   7,  973]],

       [[8855,   10],
        [  13, 1122]],

       [[8948,   20],
        [  18, 1014]],

       [[8971,   19],
        [  29,  981]],

       [[9002,   16],
        [  19,  963]],

       [[9076,   32],
        [  17,  875]],

       [[9025,   17],
        [  14,  944]],

       [[8952,   20],
        [  16, 1012]],

       [[8999,   27],
        [  17,  957]],

       [[8976,   15],
        [  40,  969]]])

In [72]:
print(sklearn.metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.98      0.97      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.96      0.98      0.97       892
           6       0.98      0.99      0.98       958
           7       0.98      0.98      0.98      1028
           8       0.97      0.98      0.98       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

